version: '3.4'
# author: Rémi Venant, <remi.venant@univ-lemans.fr>

services:
  mysqldb:
    image: mariadb:10.4
    env_file:
      - environment/prod/mysql.env
    environment:
      - MYSQL_ROOT_PASSWORD=SDFJ43shdqi324Jsdh123Jdh
    volumes:
      - mysql-data:/var/lib/mysql
      - ../databasesInit/mysql/prod:/docker-entrypoint-initdb.d:ro
    networks:
      lpdiwa-net:
        aliases:
          - mysqldb
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-pSDFJ43shdqi324Jsdh123Jdh",  "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

  mongodb:
    image: mongo:4.2
    env_file:
      - environment/prod/mongo.env
    volumes:
      - mongo-data:/data/db
      - ../databasesInit/mongo/prod:/docker-entrypoint-initdb.d:ro
    networks:
      lpdiwa-net:
        aliases:
          - mongodb
    restart: always
    healthcheck:
      test: ["CMD", "mongo", "--eval", "'db.runCommand(\"ping\").ok'", "--quiet"]
      interval: 60s
      timeout: 10s
      retries: 10
      start_period: 20s

  symfony:
    build:
      context: ./symfony
    env_file:
      - environment/prod/symfony.env
    volumes:
      - ./symfony/php-prod.ini:/usr/local/etc/php/php.ini:ro
      - ../site:/var/www/site
      - site-vendor:/var/www/site/vendor
    working_dir: /var/www/site
    networks:
      lpdiwa-net:
        aliases:
          - symfony
    restart: always
    command: bash -c "composer install && php-fpm"

  http:
    image: nginx:1.19-alpine
    depends_on:
      - symfony
    volumes:
      - ../site:/var/www/site:ro
      - ./http/server-prod.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      lpdiwa-net:
        aliases:
          - httpsrv
    ports:
      - 80:80
    restart: always

volumes:
  site-vendor:
  mysql-data:
  mongo-data:

networks:
  lpdiwa-net:
